risc0/zirgen

zirgen/circuit/bigint/op_tests.cpp
zirgen/circuit/bigint/op_tests.h

this was fixed in risczero-wip, but either didn't land or otherwise didn't make it to the zirgen repo

delete unused test support function which prompts a compiler warning

---

zirgen/dsl/passes/GenerateLayout.cpp

BitVector api uses ints for index values, but capacity is a size_t, so we need a cast to make it happy (and I added a guarding assertion)

satisfy compiler's concern about mixed signed/unsigned comparison

---

zirgen/dsl/passes/GenerateLayout.cpp

Modify layout to not use 'pinning' concept.  Instead for each aliased value, 'preallocate' it when processing the appropriate ancestor component

ZIR-163: Modify layout to not use 'pinning' concept

---

zirgen/Conversions/Typing/ZhlComponent.cpp
zirgen/dsl/examples/Fp.h

No significant problems addressed here, but it's nice to keep the compile log clean, so that new issues stand out when they arise.

ZIR-165: address a couple of minor compiler warnings

---

zirgen/circuit/fib/Cargo.toml
zirgen/dsl/Cargo.toml

The Dependabot PRs (#1 #2) seem to fail in CI due to not having a Linear API key. We could probably look into fixing that somehow, but I'd like to just clear out these PRs for now.

ZIR-166: Manual Dependabot updates

---

zirgen/Conversions/Typing/ZhlComponent.cpp
zirgen/Dialect/ZHLT/IR/TypeUtils.cpp
zirgen/Dialect/ZStruct/IR/Enums.td
zirgen/Dialect/ZStruct/IR/Types.cpp
zirgen/circuit/keccak/keccak.zir
zirgen/compiler/layout/collect.cpp
zirgen/compiler/layout/improve.cpp
zirgen/compiler/layout/rebuild.cpp
zirgen/compiler/layout/viz.cpp
zirgen/dsl/ast.cpp
zirgen/dsl/ast.h
zirgen/dsl/driver.cpp
zirgen/dsl/lower.cpp
zirgen/dsl/parser.cpp
zirgen/dsl/passes/GenerateAccum.cpp
zirgen/dsl/passes/GenerateLayout.cpp
zirgen/dsl/test/args.zir
zirgen/dsl/test/args2.zir
zirgen/dsl/test/args3.zir
zirgen/dsl/test/repro/extern_loop_with_accum.zir
zirgen/dsl/test/repro/generate_layout_column_reuse_1.zir
zirgen/dsl/test/repro/generate_layout_column_reuse_2.zir
zirgen/dsl/test/use_once_memory.zir
zirgen/dsl/test/utils.cpp
zirgen/dsl/test/utils.h

This allows each arm to do independent register allocation.  Note: a couple of syntax/semantic changes were required:
1) Any use of 'argument' components now requires a major mux
2) The major mux must be unique for any top level component
3) The major mux is denoted by the use of ->! instead of ->
4) All selector values of a major mux must coerce to NondetReg (i.e. must be registers)
This required a few minor changes to tests.

ZIR-172: Stop propagation of arguments at the major mux

---

zirgen/dsl/driver.cpp
zirgen/dsl/examples/calculator.cpp.inc
zirgen/dsl/examples/calculator.ir
zirgen/dsl/examples/calculator.rs.inc
zirgen/dsl/examples/fibonacci.rs.inc

Move CSE pass immediately after generation of backs for experimentally-determined best combined compile & test time performance.
This addresses ZIR-157.

ZIR-168: improve compile performance by computing CSE earlier

---

zirgen/Dialect/BigInt/IR/Eval.cpp

See tzerrell's change ee85492, also 03a74d2 in the risc0 repo.

ZIR-209: update BigInt eval's bytepoly multiply for correct number of coefficients

---

zirgen/Dialect/BigInt/Bytecode/decode.cpp

IntegerAttr constructor fails when given a BigInt type. Use the typeless constructor instead, accepting an APSInt value wrapping our original APInt.

ZIR-213: generate IntegerAttr typelessly from APSInt, not from APInt

---

zirgen/Dialect/BigInt/IR/Eval.h
zirgen/circuit/bigint/bibc-exec.cpp

Show that the Rust and C++ implementations of the bigint evaluator produce identical results by having the C++ implementation of `bibc-exec` convert its output into Montgomery form, as the Rust version does.

ZIR-214: convert output values into montgomery form to match rust implementation

---

zirgen/Dialect/BigInt/Bytecode/decode.cpp
zirgen/Dialect/BigInt/Bytecode/file.cpp
zirgen/Dialect/BigInt/Bytecode/file.h
zirgen/Dialect/BigInt/Bytecode/test/BUILD.bazel
zirgen/Dialect/BigInt/Bytecode/test/test.cpp
zirgen/Dialect/BigInt/IR/Eval.cpp

instead of generating a tmp file, you can now read from/write to a memory buffer

ZIR-215: abstract bibc file format reader & writer for use on memory buffers

---

zirgen/compiler/codegen/gen_rust.cpp

why `DenseArrayAttr::size()` returns a signed int, I have no idea: but that's what it does

ZIR-223: address compiler's nitpick about signed/unsigned comparison

---

zirgen/Dialect/BigInt/Bytecode/bibc.h
zirgen/Dialect/BigInt/Bytecode/decode.cpp
zirgen/Dialect/BigInt/Bytecode/encode.cpp
zirgen/Dialect/BigInt/Bytecode/test/test.cpp
zirgen/Dialect/BigInt/IR/Eval.cpp
zirgen/Dialect/BigInt/IR/Eval.h
zirgen/Dialect/BigInt/IR/Ops.cpp
zirgen/Dialect/BigInt/IR/Ops.td

These are the changes from the `zirgen/Dialect/BigInt` portion of Jeremy's PR #56, plus the range-check modification I suggested in `decode.cpp`.

ZIR-227: add load & store ops to BigInt dialect (extracted from PR #56)

---

.gitignore
Cargo.lock
zirgen/circuit/fib/Cargo.toml
zirgen/circuit/keccak/Cargo.toml
zirgen/circuit/keccak/methods/guest/Cargo.lock
zirgen/dsl/Cargo.toml

Dependabot just opened a few pull requests, with CI failing because it doesn't have Linear access. This PR incorporates those changes, and will close those PRs.

ZIR-246: Dependabot updates

---

zirgen/circuit/bigint/bigint2c.cpp

A quick change to make modpow_65537 work with up to 4096-bit values (up from 3072). In the long run we're going to want to generalize and create multiple blobs and/or go via modmul, but for now this improves compatibility at a moderate performance cost.

ZIR-248: Change modpow bitwidth to 4096

---

zirgen/circuit/BUILD.bazel

Without this dependency, omitted from my previous PR, `cargo bootstrap bigint2` did not rebuild the blobs before attempting to copy them. Now it should do the right thing automatically.

ZIR-258: build the bigint blobs when building //zirgen/circuit

---

zirgen/circuit/bigint/README.md

Adds a short readme discussing the contents of `zirgen/circuit/bigint`

ZIR-259: Add readme for bigint circuits

---

zirgen/Dialect/ZStruct/IR/Types.cpp
zirgen/Dialect/ZStruct/IR/Types.h
zirgen/Dialect/Zll/IR/test/comptypes.mlir

As part of a different project, I plan to add metadata to the `FieldInfo` struct; in the meantime, we might as well drop this ancient relic of an original concept for ZStruct which we never actually followed up on.

ZIR-278: the storage kind field has never been used anywhere for any purpose

---

zirgen/Conversions/Typing/ZhlComponent.cpp
zirgen/Dialect/ZHLT/IR/Dialect.cpp
zirgen/Dialect/ZHLT/IR/TypeUtils.cpp
zirgen/compiler/picus/BUILD.bazel
zirgen/compiler/picus/picus.cpp
zirgen/compiler/picus/picus.h
zirgen/compiler/picus/test/BUILD.bazel
zirgen/compiler/picus/test/alias_layout_1.zir
zirgen/compiler/picus/test/log.zir
zirgen/compiler/picus/test/map.zir
zirgen/dsl/BUILD.bazel
zirgen/dsl/ast.cpp
zirgen/dsl/ast.h
zirgen/dsl/driver.cpp
zirgen/dsl/lexer.h
zirgen/dsl/lower.cpp
zirgen/dsl/parser.cpp
zirgen/dsl/parser.h
zirgen/dsl/passes/BUILD.bazel
zirgen/dsl/passes/InlineForPicus.cpp
zirgen/dsl/passes/Passes.h
zirgen/dsl/passes/Passes.td
zirgen/dsl/test/alias_layout_hint_1.zir
zirgen/dsl/test/utils.cpp
zirgen/dsl/test/utils.h

I've written a bunch of code for Picus integration, and thought it would be good to open a PR at an intermediate step so it's not so ridiculously enormous. Summary of changes:
* Added "attribute" syntax for components, modeled after Rust attributes. Currently, the only supported attribute is `picus`:
```
#[picus]
component Foo(x: Val) {
a := Reg(x);
}
```
* Added `--emit=picus` option which emits picus code for components with the `picus` attribute and their transitive dependencies
* Added scaffolding for Picus lowering, and implemented a medium-sized chunk of it
* Created a new `InlineForPicusPass` which inlines some components to improve Picus performance (Shankara's suggestion, and doubles as a stopgap for a missing Picus feature)

ZIR-280: Keccak2 InitCycle is deterministic 🎉

---

zirgen/circuit/bigint/test/BUILD.bazel

`bazel test --test_verbose_timeout_warnings` revealed that all of these new operation tests should be marked "small", since they do not need anywhere near 60 seconds to run.

ZIR-296: make bazel happy by adding size specifiers for the op tests

---

zirgen/circuit/rv32im/v2/dsl/decode.zir
zirgen/circuit/rv32im/v2/dsl/inst_div.zir
zirgen/circuit/rv32im/v2/dsl/inst_ecall.zir
zirgen/circuit/rv32im/v2/dsl/inst_p2.zir
zirgen/circuit/rv32im/v2/dsl/lookups.zir
zirgen/circuit/rv32im/v2/dsl/mem.zir

Fix all open soundness issues uncovered by Picus testing.

ZIR-305: Audit fixes

---

zirgen/circuit/rv32im/v2/dsl/decode.zir

Hi!
Updated the broken link in [decode.zir](https://github.com/risc0/zirgen/blob/main/zirgen/circuit/rv32im/v2/dsl/decode.zir#L7):
https://github.com/jameslzhu/riscv-card/releases/download/latest/riscv-card.pdf
This change aligns with the update made in [commit 6628be3](https://github.com/jameslzhu/riscv-card/commit/6628be3cca53b590896ae7a72a9d9446eee7bfd1).

fix: broken link decode.zir

---

zirgen/circuit/rv32im/v2/dsl/inst_ecall.zir

This could be checked in the kernel rather than in the circuit.

ZIR-318: Drop restriction on fd for host_read ecall

---

zirgen/Dialect/BigInt/Bytecode/file.cpp

spotted a warning I hadn't noticed before: even though we always overwrite the contents of these arrays, it doesn't hurt to explicitly initialize them, thereby pacifying the `maybe-uninitialized` checker.

ZIR-327: make the compiler happy by explicitly value-initializing std::array<>s

---

zirgen/circuit/keccak2/cpp/wrap_dsl.cpp
zirgen/compiler/r1cs/wtnsfile.cpp

Disable a dozen or so persistent warnings which clutter up the compiler output without providing actionable information.

ZIR-328: clean up the compile a little more: fix warnings

---

rust-toolchain.toml
zirgen/bootstrap/src/main.rs
zirgen/circuit/fib/src/lib.rs
zirgen/circuit/fib/src/taps.rs
zirgen/compiler/codegen/rust/taps.tmpl.rs
zirgen/dsl/examples/calculator/cpu.rs
zirgen/dsl/examples/calculator/main.rs
zirgen/dsl/examples/calculator/taps.rs
zirgen/dsl/src/codegen/mod.rs
zirgen/dsl/src/codegen/taps.rs
zirgen/dsl/src/lib.rs

Updates a few clippy errors and fixes clippy errors in generated code for risc0
NOTE: I am still seeing some errors from generated code in Calculator but I think they can stay for now?

ZIR-336: Updated to rust 1.83

---

zirgen/bootstrap/src/main.rs
zirgen/circuit/bigint/BUILD.bazel
zirgen/circuit/bigint/basic.cpp
zirgen/circuit/bigint/basic.h
zirgen/circuit/bigint/bigint2c.cpp

This adds a bigin2 program which multiplies two 256-bit numbers without doing modular arithmetic.
Out plan is to use this new program and modmul_256 in the v2 executor to "emulate" the bigint1 calls.
See https://github.com/risc0/risc0/pull/2816

ZIR-339: Add mul_256 bigint2 program and copy modmul_256 to new additional destination

---

zirgen/circuit/rv32im/v2/dsl/inst_control.zir
zirgen/dsl/parser.cpp
zirgen/dsl/test/parser.cpp
zirgen/dsl/test/repro/if_without_else.zir

a fossilized bug
muxes need multiple arms
even lonely `if`

ZIR-344: Fix semantics of if without else

---

zirgen/Conversions/Typing/BuiltinComponents.cpp
zirgen/Main/BUILD.bazel
zirgen/compiler/codegen/BUILD.bazel
zirgen/compiler/codegen/codegen.cpp
zirgen/compiler/stats/BUILD.bazel
zirgen/compiler/stats/OpStats.cpp
zirgen/compiler/stats/OpStats.h
zirgen/dsl/examples/fibonacci.rs.inc
zirgen/dsl/passes/SemanticLowering.cpp

* Add --op-stats flag to enable printing of location statistics for the validity evaluation function (`eval_check`)
* Add "builtin" `NameLoc`s to builtin components instead of `UnknownLoc` so they show up
* Add "All Constraints" `NameLoc` to constraint evaluation function instead of `UnknownLoc` so they show up

ZIR-347: Add circuit location statistics for validity evaluation function

---

zirgen/circuit/keccak/cycle_counter.zir
zirgen/circuit/keccak/predicates.cpp
zirgen/circuit/keccak/top.zir
zirgen/circuit/predicates/predicates.cpp
zirgen/circuit/predicates/predicates.h

Without this change, the Keccak circuit has a nondeterministic `isFirst` register that marks the first cycle of the computation. An honest prover should set this register to 1 on some cycle, and 0 on all other cycles, noting that STARK traces are equivalent up to rotation (that is, we can assume loss of generality that "the first cycle" is the one we expect it to be). There is a relatively complicated, informal argument that leaving this register underconstrained is a fine thing to do, because it means that the prover has either populated the witness with the computation of the same hash multiple times, or that the prover knows a hash collision which we take to be computationally infeasible.
Jeremy and I agreed that it makes sense to lock this down a bit more and switch to a stricter …

ZIR-352: Use cycle counter in Keccak circuit for provable determinism

---

zirgen/Dialect/ZHLT/IR/BUILD.bazel
zirgen/Dialect/ZHLT/IR/ComponentOps.td
zirgen/Dialect/ZHLT/IR/Interfaces.td
zirgen/Dialect/ZHLT/IR/Ops.cpp
zirgen/Dialect/ZHLT/IR/ZHLT.h
zirgen/dsl/passes/GenerateAccum.cpp
zirgen/dsl/passes/SemanticLowering.cpp

This change cleans up some superfluous attributes on `ZFuncOp`s and `ZCallOp`s, namely `input_segment_sizes`, `result_segment_sizes`, and `callee_type`. For example, here's the `Top` component of our `sum.zir` test without this change:
```
zhlt.component @Top() -> !zstruct$Top attributes {input_segment_sizes = array<i32: 0, 0>, result_segment_sizes = array<i32: 1>} {
%0 = zll.const 6
%1 = zll.const 3
%2 = zll.const 1
%3 = zll.const 2
%4 = zstruct.array[%2, %3, %1 : !zll.val<BabyBear>, !zll.val<BabyBear>, !zll.val<BabyBear>]
%5 = zhlt.construct @"Sum<3>"(%4) : (!zstruct.array<!zll.val<BabyBear>, 3>) -> !zstruct$Sum3C33E {callee_type = (!zstruct.array<!zll.val<BabyBear>, 3>) -> !zstruct$Sum3C33E, input_segment_sizes = array<i32: 1, 0>, operandSegmentSizes = array<i32: 1, 0>, …
```

ZIR-359: [NFC] Clean up superfluous attributes

---

zirgen/Conversions/Typing/BuiltinComponents.cpp
zirgen/docs/A1_Builtin_Components.md
zirgen/dsl/examples/fibonacci.rs.inc
zirgen/dsl/test/repro/div.zir

The old implementation of `Div` is broken, since the result of `Inv` is nondeterministic and it always uses this value in a constraint. This means `Div` only worked when the denominator was a constant, such that the inverse in the constraint could be folded. Otherwise, this leads to a `zll.inv` in the validity polynomial computation which produces a cryptic diagnostic about an "illegal operation." 
```
function Div(lhs: Val, rhs: Val) {
reciprocal := Inv(rhs);
reciprocal * rhs = 1;
reciprocal * lhs
}
```
The new implementation lifts this restriction, and makes `Div` purely nondeterministic. It is simply
```
function Div(lhs: Val, rhs: Val) {
lhs * Inv(rhs)
}
```

ZIR-361: Fix useless constraint in division component

---

.github/workflows/main.yml

Bumps checkout to v4 for future-proofing against Node 20 runner updates. Workflows compile the same.

ci: bump actions/checkout to v4

---

zirgen/compiler/picus/picus.cpp

Because Zirgen emits components for everything, including builtins, I made the Picus extractor a little bit too eager to extract dependencies, namely:
* anything marked `picus_inline` (necessary)
* anything constructed by a component that is extracted (necessary)
* anything used as a parameter by a component that is extracted to Picus (unnecessary)
Turning off the third one shouldn't cause any problems because Picus' analysis doesn't need to inspect where parameters come from. It does, however, save us from needing to generate Zirgen components in v3 for e.g. `Val` and `Reg`.

Picus doesn't require modules for parameters
